DROP TABLE IF EXISTS "Commands";
CREATE TABLE "Commands" ("GameId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "Command" BLOB);
DROP TABLE IF EXISTS "GameInfos";
CREATE TABLE "GameInfos" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "GameInfo" BLOB);
DROP TABLE IF EXISTS "GameModels";
CREATE TABLE "GameModels" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "GameModel" BLOB);
DROP TABLE IF EXISTS "Users";
CREATE TABLE "Users" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "User" BLOB);
